### ISSUE TITLE
Old Twitter legacy

### ISSUE THREAD

**Issue by andika207** [dimdenGD/OldTwitter#21]
it requires chrome 88+
is there a legacy edition for older chrome versions ?

**Comment by dimdenGD** [comment]
Chrome version of extension uses Manifest V3. Firefox one uses Manifest V2 which is much older version and it theoretically could work on older Chrome. So try getting [OldTwitterFirefox.zip](https://github.com/dimdenGD/OldTwitter/releases/download/v1.6.5.1/OldTwitterFirefox.zip) and installing it manually (you won't receive updates though). I don't know if it'll work.
Also there might be some issues about my code being too modern for older chrome, but I don't really know to what extent, I tried to use modern features as least as possible

**Comment by andika207** [comment]
Manifest v3 sucks and will kill many good extensions that won't be updated because they don't need to.
the clowns at Alphabet are doing this with Android as well.
 https://arstechnica.com/gadgets/2022/05/apple-and-googles-outdated-apps-ban-would-cut-each-store-by-a-third/

**Comment by dimdenGD** [comment]
I don't know how is that relevant to this discussion. Manifest v3 works fine for my extension and I didn't have any issues. It's required to be listed on Chrome Web Store so I'll continue using it. I've made a [script](https://github.com/dimdenGD/OldTwitter/blob/master/pack.js) to build Manifest v2 version of extension because Firefox doesnt support Manifest v3. As I mentioned before it's your only chance to make it work on older versions, though I don't understand what's the issue with just updating and being able to use all new extensions.

**Comment by andika207** [comment]
WinXP doesn't support the latest chrome versions (unless you make use of unstable patches) 
so, many updated extensions won't run on older chromium based browsers anymore.
it's ok if you don't want to get your addon to run on pre-88 chrome version
I won't move on to W11 or similar shit.
