### ISSUE TITLE
Blue checks not showing on the timeline

### ISSUE THREAD

**Issue by cobrabr** [dimdenGD/OldTwitter#277]
**Describe the bug**
Blue checkmarks are not showing in the timeline (though they do show in the account's profile page).

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/724969/91eaac70-287a-4fe5-9af3-8309bb61d083)
![image](https://github.com/dimdenGD/OldTwitter/assets/724969/f3a88dea-a639-4b5f-a11b-30e8b31f535d)

**Browser**
Chrome 114.0.5735.248 (64-bit)

**Links**
Happens with all blue checks, from what I could see.

**OldTwitter version**
v1.7.3.4 (recently installed from the Chrome store... I tried using the update button, but it didn't update to 1.7.4).

**Comment by iiv3** [comment]
I did a bisect and landed on 5d51a37331c790e149b16308e9d0c4ece7d3552c as first bad commit. There is nothing obvious or directly linked to checkmarks in that commit.

Interesting enough my first attempt landed me on much later commit 9508bd0a5f096861eec7e32dd013e6e1e6a230ec , because pinned tweets seem to have had a separate code and kept showing the checkmark long after normal tweets had lost them.

BTW, is it still possible to distinguish legacy and twitter-blue checkmarks?

**Comment by cobrabr** [comment]
Just wanted to add that the same issue happens on Firefox, with OldTwitter v1.7.4.3.

**Comment by dimdenGD** [comment]
Fixed
