### ISSUE TITLE
'Request requires matching CSRF cookie and header' errors after trying to switch accounts

### ISSUE THREAD

**Issue by zulc22** [dimdenGD/OldTwitter#34]
`This request requires a matching csrf cookie and header. at 1611887966606991360 (OldTwitter v1.6.5.7)` when loading tweets, in the worst cases.

Usually, I will be able to load the timeline, but have the appearance that I'm logged in to another account, or have the wrong timeline and notifications, but interacting with tweets will end up showing a similar error.

On Chromium, Windows. Firefox seems to have very similar issues but remains hardly usable for me. Fresh install of Firefox Beta, used it for 10 minutes and it was fine, but after about 30 it became unusably slow. Maybe I should make another issue for that.

**Comment by dimdenGD** [comment]
I've tried to switch account and use twitter a few times and I couldn't replicate the issue. Using Firefox (not Beta) for a while also doesn't cause me any lags. The only way possible for me to check your issue is when you start getting big lags press F12, go to Perfomance tab and hit "Start recording", then proceed using Twitter for like 20 seconds with all these lags, then press "Capture recording", you'll get sent to other tab, on top-right of it there will be "Upload Local Profile", check all checkmarks in additional data and hit Upload and send the link here.

**Comment by dimdenGD** [comment]
CSRF error was fixed
