### ISSUE TITLE
Tweets don't load when tapped or clicked at certain spots

### ISSUE THREAD

**Issue by Rokotallion** [dimdenGD/OldTwitter#416]
**Describe the bug**
Sometimes a tweet has spots where it doesn't register and won't load the tweet. It frequently happens on mobile, sometimes maybe on PC.

sidenote: tapping the date created can load the tweet as a workaround. Tapping at the left side of the tweet below the avatar helps too. It maybe that text elements are obscuring the tap from registering.

**Screenshots**

https://github.com/dimdenGD/OldTwitter/assets/79259221/a1b26aa0-b2d5-4c35-bf90-78ea0abbffbe

**Browser**
Kiwi Browser

**Links**
Link to profile/tweet or other page where bug happens.

**OldTwitter version**
1.7.5.2

**Comment by dimdenGD** [comment]
This is normal behavior to support selecting text, dont click on text to open tweet

**Comment by iiv3** [comment]
Actually, I would appreciate an option to revert that behavior.

Hitting the right spot(s) is a bit harder on mobile,
especially when there is no actual visual indications where the active zones are.

Also, selecting text is quite rare event. It's more common to open a post to read the thread/comments.

You also should be able to select the tweet's text once you've opened it.

**Comment by dimdenGD** [comment]
I think there's plenty of empty space on sides of the tweet to click on it

**Comment by TorutheRedFox** [comment]
tweets should open in this case in onmouseup if cursor hasn't moved more than a few pixels to let people select text just fine but also get the expected behavior of a tweet opening when clicked

> I think there's plenty of empty space on sides of the tweet to click on it
the empty space is pretty small in replies

**Comment by iiv3** [comment]
> I think there's plenty of empty space on sides of the tweet to click on it

It depends on the tweet.

Actually the margins are really small and the most consistent free space is under the profile picture or on the side of the (reply. retweet, like, etc) buttons.
That also increases the risk of clicking on the neighboring tweet or pfp.

The real problem is that it is counter intuitive. I had no idea that only the text is not clickable until you wrote it here. 
As I said before, there is no indication what is clickable and what is not. When hovering with the mouse, the pointer is always a hand, and never a text selection tool.

**Once again, we are asking to make it optional.**
If always selecting text is so important for you, keep it as option.

> tweets should open in this case in onmouseup if cursor hasn't moved more than a few pixels to let people select text just fine but also get the expected behavior of a tweet opening when clicked

That's exactly what new-twitter and blue-sky do.
