### ISSUE TITLE
Downloaded video can't be played on pc

### ISSUE THREAD

**Issue by bidfor** [dimdenGD/OldTwitter#623]
The downloaded video can't be played on pc. Doesn't work on both windows media player and VLC player.  A workaround I found is to repair the video with https://webbrowsertools.com/repair-video/  and the video can be played again.  Anyone else having this issue?

**Comment by dimdenGD** [comment]
Specific video or all videos

**Comment by dimdenGD** [comment]
can't reproduce, the video downloaded plays fine for me

**Comment by AlttiRi** [comment]
Most likely he uses VLC player on Windows/Android, or an Apple device.
There is a playback issue on them because of Twitter's new "broken" mp4 muxer.

The only way to fix it is to remux the video
```bash
ffmpeg.exe -i video.mp4 -c copy -map 0 -map_metadata 0 video.remux.mp4
```
_or just hope that Twitter's team will fix their software, either Apple/VLC will add the support for such mp4 containers._

https://github.com/AlttiRi/twitter-click-and-save/issues/37#issuecomment-1850997495
