### ISSUE TITLE
Unable to edit profile

### ISSUE THREAD

**Issue by ashjaylk** [dimdenGD/OldTwitter#67]
I'm experiencing an issue where I'm unable to edit my profile on Twitter. Whenever I click on the "Edit profile" button, it directs me to **https://twitter.com/settings/profile**, but the page just hangs forever and doesn't load. 
I've tried this on **_Microsoft Edge Version 112.0.1722.58 (Official build) (64-bit)_** and the issue persists.

### Steps to reproduce:

1. Log in to Twitter.
2. Click on the profile icon in the top right corner.
3. Click on the "Edit profile" button.
4. Observe that the page redirects to https://twitter.com/settings/profile and hangs indefinitely.

### Expected behavior:

I should be directed to the Twitter profile settings page where I can edit my profile information.

### Actual behavior:

I am directed to https://twitter.com/settings/profile, which hangs indefinitely and prevents me from editing my profile.

### Additional information:

I have tried clearing my browser cache and cookies, but the issue persists. 

Please let me know if you need any further information or assistance in resolving this issue.

**Comment by dimdenGD** [comment]
This was fixed already, please wait until update releases (up to a week). Temporary fix is to disable extension when you need to go on new twitter and enable it back when did what you wanted

**Comment by scarlion1** [comment]
@dimdenGD can you help why is my "Edit Profile" button linking to https://twitter.com/settings/profile?newtwitter=true which is being forced?  I tried to delete `?newtwitter=true` from the URL but it just comes back.  I tried changing `true` to `false` but it goes back to `true`.  Although the URL says `settings/profile?newtwitter=true`, it doesn't actually load my profile settings, I just see the (newtwitter) timeline... I believe there should be an overlay on top with my profile settings but that isn't displayed.  A similar thing (URL is updated but page content doesn't change/hangs) happens when I try to open a picture attached to a tweet (newtwitter only).

**Comment by scarlion1** [comment]
Seems related to something uBlock Origin was filtering, maybe from ads-twitter.com?  Turning off uBO on twitter.com fixed the problem.
