### ISSUE TITLE
Odd behavior with quotation marks in alt text

### ISSUE THREAD

**Issue by 175fd6cd** [dimdenGD/OldTwitter#792]
**Describe the bug**
If there is a quotation mark at any point in an image's alt text, it and all text after it will be cut off.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/61462684/cfdedbaf-27d8-4e3e-8537-9dff2499638d)
![image](https://github.com/dimdenGD/OldTwitter/assets/61462684/4a0739d3-8fe7-4b77-a499-81d78a34ff56)

**Browser**
Waterfox G6.0.14 (64-bit)

**Links**
n/a

**OldTwitter version**
v1.8.4.3

**Comment by wiichicken** [comment]
Bumping this. I noticed that too. This could easily be fixed by replacing any quotation marks in alt text with `&quot;`.

![vivaldi_CAgsp2u4Hr](https://github.com/dimdenGD/OldTwitter/assets/50886841/63550839-85e3-434c-98be-e50cc8ec66d3)
![vivaldi_e24rD73P1I](https://github.com/dimdenGD/OldTwitter/assets/50886841/507677e4-35fb-404f-97bf-d32cb5a1bcd7)

**Comment by dimdenGD** [comment]
Can you link to tweet with " in alt?
